name: FiddyCraft
main: io.github.FiddyPercent.fiddycraft.FiddyCraft
version: 1.1

commands:
    vfname:
      description: Adds a first name to the Villager name pool.
      usage: /addVname <name>
      permission: FiddyCraft.test
      permission-message: You don't have permission fool
    setJail:
      description: uses your location as the jail spawn point
      usage: /setJail 
      permission: FiddyCraft.test
      permission-message: You don't have permission fool
    Jail:
      description: sends player to jail.
      usage: /Jail <name> <Labor points>
      permission: FiddyCraft.Judge
      permission-message: You don't have permission
    FCreload:
      description: reloads the plugin.
      usage: /fcreload 
      permission: FiddyCraft.op
      permission-message: You don't have permission