name: FiddyCraft
main: io.github.FiddyPercent.fiddycraft.FiddyCraft
version: 1.0

commands:
    Test:
      description: This is a demo command.
      usage: /<command>
      permission: FiddyCraft.test
      permission-message: You don't have permission fool