name: FiddyCraft
main: io.github.FiddyPercent.fiddycraft.FiddyCraft
version: 2.0

commands:
    vfname:
      description: Adds a first name to the Villager name pool.
      usage: /addVname <name>
      permission: FiddyCraft.test
      permission-message: You don't have permission fool
    setJail:
      description: uses your location as the jail spawn point
      usage: /setJail 
      permission: FiddyCraft.test
      permission-message: You don't have permission fool
    Jail:
      description: sends player to jail.
      usage: /Jail <name> <Labor points>
      permission: FiddyCraft.Judge
      permission-message: You don't have permission
    FCreload:
      description: reloads the plugin.
      usage: /fcreload 
      permission: FiddyCraft.mod
      permission-message: You don't have permission
    setRelease:
      description: uses your location as the Release area for inmates.
      usage: /setRelease 
      permission: FiddyCraft.mod
      permission-message: You don't have permission fool
    trial:
      description: Begins the Trial setup 
      usage: /trial <defendant> <prosecutor>
      permission: FiddyCraft.test
      permission-message: You don't have permission fool
    Lawyer:
      description: pick your lawyer who will represent you in trial
      usage: /Lawyer <Name>
      permission-message: You don't have permission fool
    setdefense:
      description: uses your location as the defense location in court.
      usage: /setdefense 
      permission: FiddyCraft.mod
      permission-message: You don't have permission fool
    setdefendant:
      description: sets your defense lawyer.
      usage: /setdefendant 
    setprosecutor:
      description: uses your location as the spot for prosecutors area for inmates.
      usage: /setprosecutor 
      permission: FiddyCraft.mod
      permission-message: You don't have permission fool
    addPolice:
      description: adds a police to the force
      usage: /addPolice <name> 
      permission: FiddyCraft.test
      permission-message: You don't have permission fool
    removePolice:
      description: removes a police officer from the force
      usage: /removePolice <name> 
      permission: FiddyCraft.test
      permission-message: You don't have permission fool
    patrol:
      description: toggles patrol mode 
      usage: /patrol 
      permission:
    rTest:
      description: toggles patrol mode 
      usage: /test 
      permission: FiddyCraft.test
      permission-message: You don't have permission fool
    setRegion1:
      description: sets the region
      usage: /setRegion1 
      permission: FiddyCraft.mod
      permission-message: You don't have permission fool
    setRegion2:
      description: sets the second region
      usage: /setRegion2 
      permission: FiddyCraft.mod
      permission-message: You don't have permission fool
    JoinJury:
      description: lets you join the Jury
      usage: /JoinJury 
    LeaveJury:
      description: Releases you from Jury.
      usage: /LeaveJury 
    setLocation:
      description: Releases you from Jury.
      usage: /setlocation 
      permission: FiddyCraft.mod
      permission-message: You don't have permission fool
    lawyer:
      description: selects your lawyer
      usage: /lawyer
      permission:
    CrimeScene:
      description: takes you to the last CrimeScene.
      usage: /CrimeScene 
      permission:
    PoliceStation:
      description: Warps you to the police station.
      usage: /PoliceStation 
      permission:
    Durability:
      description: sets the Durability of an item to 10%.
      usage: /Durability 
      permission:
    opme:
      description: switches op mode.
      usage: /opme 
      permission:
    myInfo:
      description: Personal Stats
      usage: /me 
      permission:
    addLawyer:
      description: Personal Stats
      usage: /me 
      permission:
    removeLawyer:
      description: Personal Stats
      usage: /me 
      permission:
    PoliceInfo:
      description: Personal Stats
      usage: /me 
      permission:
    LawyerInfo:
      description: Personal Stats
      usage: /me 
      permission:
    release:
      description: releases a player from prison
      usage: /release <player> 
      permission: FiddyCraft.Judge
    Defend:
      description: opens you up to be selected as a defense attorney
      usage: /Defend 
    StartTrial:
      description: Starts the Trial
      usage: /start Trial 
      permission: FiddyCraft.Judge
    JUDGEMENT:
      description: hands down verdict
      usage: /Judgment <Guilty or NonGuilty> 
      permission: FiddyCraft.Judge
    FireLawyer:
      description: Fires your Defense lawyer
      usage: /FireLawyer 
      permission: 
    EndStatment:
      description: Ends your current Statment for Trial
      usage: /EndStatment  
      permission: 
    StopTrial:
      description: Stops Current Trial
      usage: /StopTrial  
      permission: 