name: FiddyCraft
main: io.github.FiddyPercent.fiddycraft.FiddyCraft
version: 1.1

commands:
    vfname:
      description: Adds a first name to the Villager name pool.
      usage: /addVname <name>
      permission: FiddyCraft.test
      permission-message: You don't have permission fool
      
    vlname:
      description: Adds a last name to the Villager name pool.
      usage: /addVname <name>
      permission: FiddyCraft.test
      permission-message: You don't have permission fool
    test:
      description: Adds a last name to the Villager name pool.
      usage: /addVname <name>
      permission: FiddyCraft.test
      permission-message: You don't have permission f